# path
train_path: ../data/train_dataset

# data
shuffle: True
max_seq_length: 384
pad_to_max_length: False
doc_stride: 128
max_answer_length: 30
eval_retrieval: True
num_clusters: 64
top_k_retrieval: 10
use_faiss: False

# model
model_name: klue/roberta-base

# train
seed: 42
gpus: 1
batch_size: 8
max_epoch: 10
learning_rate: 5e-5
logging_steps: 1

# wandb
wandb_use: True
entity: boost2end
project: MRC_backbone
run_name: klue/roberta-base

# cmd
overwrite_output_dir: True
