model:
  model_name_or_path: klue/roberta-large

dataset:
  dataset_name: ../data/train_dataset
  max_seq_length: 384
  pad_to_max_length: False
  doc_stride: 128
  max_answer_length: 30
  eval_retrieval: True
  num_clusters: 64
  top_k_retrieval: 10
  use_faiss: False

train:
  seed: 42
  data_seed: 42
  overwrite_output_dir: True
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 8
  num_train_epochs: 5
  learning_rate: 5e-5
  logging_steps: 1
  eval_steps: 1
  evaluation_strategy: epoch
  save_total_limit: 3

wandb:
  use: False
  entity: boost2end
  project: MRC_learning_rate
  run_name: klue/roberta-large
